<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4upc9In\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4upc9In/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4upc9In.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4upc9In\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4upc9In\App_KernelDevDebugContainer([
    'container.build_hash' => '4upc9In',
    'container.build_id' => '6922da19',
    'container.build_time' => 1748697053,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4upc9In');
