<?php

namespace Container4upc9In;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerdeleteTaskService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cKGvLGb.App\Controller\TaskController::deleteTask()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cKGvLGb.App\\Controller\\TaskController::deleteTask()'] = ($container->privates['.service_locator.cKGvLGb'] ?? $container->load('get_ServiceLocator_CKGvLGbService'))->withContext('App\\Controller\\TaskController::deleteTask()', $container);
    }
}
