<?php

namespace ContainerWVhL2hB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.el0X3q0.App\Controller\TaskController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.el0X3q0.App\\Controller\\TaskController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\TasksRepository', 'getTasksRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\TasksRepository',
        ]))->withContext('App\\Controller\\TaskController::index()', $container);
    }
}
